---
# ---------------------------------------------------------------------------------------
- name: Get cluster ID - {{ cluster_name }}
  include_tasks: get_cluster_id.yml
# ---------------------------------------------------------------------------------------
- name: Get cluster state - {{ cluster_name }}
  include_tasks: get_cluster_state.yml
  when: cluster_id is defined
# ---------------------------------------------------------------------------------------
- name: Set cluster state - {{ cluster_name }}
  include_tasks: set_cluster_availability.yml
  vars:
    cluster_availability: "powered_off"
    force_availability: true
  when: 
   - cluster_id is defined
   - cluster_get_response.json.record.state == "powered_on"
# ---------------------------------------------------------------------------------------
- name: Delete cluster - {{ cluster_name }}
  include_tasks: delete_cluster.yml
  when: cluster_id is defined
# ---------------------------------------------------------------------------------------
# END PLAYBOOK
# ---------------------------------------------------------------------------------------
