#######################################################
# 
#   Author:     Sean Hatfield
#   Date:       Feb 1 2024
# 
#   Description:  Creates an ONTAP Select cluster via an ONTAP Select Deploy instance
# 
#######################################################
---
- name: Create ONTAP Select cluster (KVM)
  hosts: selectclusters
  gather_facts: false
  serial: 1

  # -------------------
  # Read variable files
  # -------------------
  vars_files:
  # - vars_cluster.yml
  # - vars_cluster_pwd.yml
  tasks:
    - include_role:
        name: na_ots_cluster
        apply:
          delegate_to: localhost
      vars:
        # state: constructing
        deploy_pwd: "{{ hostvars[deploy_hostname]['deploy_password'] }}"
        deploy_ip: "{{ hostvars[deploy_hostname]['deploy_ip'] }}"
        monitor_deploy_job: true

